# Generated by Django 4.0.1 on 2022-01-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='aliass',
        ),
    ]
