# Generated by Django 4.0.1 on 2022-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='phoneNumber',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Stud_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admssionNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
