# Generated by Django 4.0.1 on 2022-01-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0002_parent_email_parent_parent_name_parent_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('strand', models.CharField(max_length=250, null=True)),
                ('sub_strand', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('due_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=250, null=True)),
                ('phoneNumber', models.CharField(max_length=250, null=True)),
                ('profile_image', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='admssionNumber',
            new_name='admssion_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=250, null=True)),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shule.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'complete'), ('incompleted', 'incomplete')], max_length=250, null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shule.assignment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shule.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shule.classlevel'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shule.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shule.teacher'),
        ),
    ]
