# Generated by Django 4.0.1 on 2022-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0003_assignment_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='posted_date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='assignmentstatus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
