# Generated by Django 4.0.1 on 2022-01-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0004_rename_posted_date_assignment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
