# Generated by Django 4.0.1 on 2022-01-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0008_rename_assignment_class_student_class_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='parento',
        ),
    ]
