# Generated by Django 4.0.1 on 2022-01-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0009_rename_parent_student_parento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parento',
            new_name='parent',
        ),
    ]
